from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from repertoire_explorer import AnimalLexBundle, load_bundle
from webapp.charts import (
    call_count_distribution_chart,
    form_meaning_chart,
    keyword_frequency_chart,
    pmi_chart,
    prediction_chart,
    species_matrix_chart,
)
from webapp.pages import call_display_labels, species_display_labels


DEFAULT_BUNDLE = ROOT / "artifacts" / "animallex" / "latest"
DEFAULT_FIGURE_DIR = ROOT / "paper" / "figures" / "generated"
DEFAULT_RESULTS_TEX = ROOT / "paper" / "generated_results.tex"


def load_analysis_bundle(path: Path | str = DEFAULT_BUNDLE) -> AnimalLexBundle:
    return load_bundle(path)


def _latex_integer(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def _macro(name: str, value: Any, *, xspace: bool = True) -> str:
    suffix = r"\xspace" if xspace else ""
    return rf"\newcommand{{\{name}}}{{{value}{suffix}}}"


def _p_text(value: float) -> str:
    return "<0.001" if value < 0.001 else f"={value:.3f}"


def _keyword_lookup(rows: list[dict[str, Any]]) -> dict[str, int]:
    return {str(row["keyword"]): int(row["count"]) for row in rows}


def render_results_tex(bundle: AnimalLexBundle, output_path: Path | str) -> None:
    """Write manuscript numbers from the unfiltered analysis in the shared bundle."""
    output_path = Path(output_path)
    overview = bundle.analysis["overview"]
    form = bundle.analysis["form_meaning"]
    prediction = bundle.analysis["prediction"]
    pmi = bundle.analysis["pmi"]
    motifs = bundle.analysis["motifs"]
    semantic_counts = _keyword_lookup(overview["semantic_keywords"])
    acoustic_counts = _keyword_lookup(overview["acoustic_keywords"])
    class_counts = {}
    for row in overview["species_counts"]:
        class_name = str(row["class"])
        class_counts[class_name] = class_counts.get(class_name, 0) + 1

    n_calls = int(overview["n_calls"])
    lines = [
        "% Generated by paper_code/bundle_render.py from the same unfiltered bundle",
        "% consumed by the web app. Do not edit these values by hand.",
        _macro("nspecies", _latex_integer(int(overview["n_species"]))),
        _macro("ncalls", _latex_integer(n_calls)),
        _macro("ncallpairs", _latex_integer(n_calls * (n_calls - 1) // 2)),
        _macro("nfamilies", _latex_integer(int(prediction["n_families"]))),
        _macro("nmammals", _latex_integer(class_counts.get("Mammalia", 0))),
        _macro("nbirds", _latex_integer(class_counts.get("Aves", 0))),
        _macro("namphibians", _latex_integer(class_counts.get("Amphibia", 0))),
        _macro("npermutations", _latex_integer(int(form["n_permutations"]))),
        _macro("nfolds", _latex_integer(int(prediction["n_folds"]))),
        _macro("nmotifs", _latex_integer(int(motifs["n_motifs"]))),
        _macro("motifacousticthreshold", f"{motifs['criteria']['minimum_acoustic_similarity']:.2f}"),
        _macro("motifsemanticthreshold", f"{motifs['criteria']['minimum_semantic_similarity']:.2f}"),
    ]

    for macro_name, keyword in (
        ("nattention", "attention"),
        ("ncontact", "contact"),
        ("ngroupcoordination", "group_coordination"),
        ("naffiliation", "affiliation"),
        ("nalarm", "alarm"),
        ("nshort", "short"),
        ("nrepetitive", "repetitive"),
        ("ntonal", "tonal"),
    ):
        source = acoustic_counts if keyword in acoustic_counts else semantic_counts
        lines.append(_macro(macro_name, _latex_integer(source[keyword])))

    group_macros = {
        "within species": "WithinSpecies",
        "same family": "SameFamily",
        "different families": "DifferentFamilies",
    }
    for group, suffix in group_macros.items():
        values = form["groups"][group]
        lines.extend(
            [
                _macro(f"r{suffix}", f"{values['r']:.2f}"),
                _macro(f"p{suffix}", _p_text(float(values["p"]))),
                _macro(f"n{suffix}Pairs", _latex_integer(int(values["n_pairs"]))),
            ]
        )

    for condition in prediction["conditions"]:
        condition_key = condition["key"]
        suffix = {
            "held_out_calls": "HeldOutCalls",
            "held_out_species": "HeldOutSpecies",
            "held_out_families": "HeldOutFamilies",
        }[condition_key]
        for model in prediction["models"]:
            model_suffix = {
                "random": "Random",
                "retrieval": "Retrieval",
                "ridge": "Ridge",
            }[model]
            for metric in ("cosine", "mrr"):
                value = prediction["results"][condition_key][model][metric]["mean"]
                metric_suffix = "Cosine" if metric == "cosine" else "MRR"
                lines.append(
                    _macro(f"{model_suffix}{suffix}{metric_suffix}", f"{value:.3f}")
                )

    pmi_cells = [
        (float(pmi["matrix"][i][j]), pmi["acoustic_keywords"][i], pmi["semantic_keywords"][j])
        for i in range(len(pmi["acoustic_keywords"]))
        for j in range(len(pmi["semantic_keywords"]))
    ]
    strongest = max(pmi_cells)
    weakest = min(pmi_cells)
    lines.extend(
        [
            _macro("pmiStrongest", f"{strongest[0]:.2f}"),
            _macro("pmiStrongestAcoustic", strongest[1].replace("_", r"\_")),
            _macro("pmiStrongestSemantic", strongest[2].replace("_", r"\_")),
            _macro("pmiWeakest", f"{weakest[0]:.2f}"),
            _macro("pmiWeakestAcoustic", weakest[1].replace("_", r"\_")),
            _macro("pmiWeakestSemantic", weakest[2].replace("_", r"\_")),
        ]
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def render_figures(bundle: AnimalLexBundle, output_dir: Path | str) -> None:
    """Export the exact Plotly figures constructed by the web app."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    overview = bundle.analysis["overview"]
    figures = {
        "overview_semantic.pdf": (
            keyword_frequency_chart(
                overview["semantic_keywords"], "Semantic functions", limit=18
            ),
            700,
        ),
        "overview_acoustic.pdf": (
            keyword_frequency_chart(
                overview["acoustic_keywords"], "Acoustic features", limit=18
            ),
            700,
        ),
        "overview_repertoire_sizes.pdf": (
            call_count_distribution_chart(overview["call_count_distribution"]),
            900,
        ),
        "form_meaning.pdf": (
            form_meaning_chart(
                bundle.analysis["form_meaning"], call_display_labels(bundle)
            ),
            1_000,
        ),
        "prediction.pdf": (prediction_chart(bundle.analysis["prediction"]), 1_200),
        "species_matrix.pdf": (
            species_matrix_chart(
                bundle.analysis["species_matrix"], species_display_labels(bundle)
            ),
            1_100,
        ),
        "pmi.pdf": (pmi_chart(bundle.analysis["pmi"]), 1_000),
    }
    for name, (figure, width) in figures.items():
        figure.write_image(output_dir / name, width=width, height=figure.layout.height)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render paper figures and numbers from the shared AnimalLex bundle."
    )
    parser.add_argument("--bundle", type=Path, default=DEFAULT_BUNDLE)
    parser.add_argument("--figure-dir", type=Path, default=DEFAULT_FIGURE_DIR)
    parser.add_argument("--results-tex", type=Path, default=DEFAULT_RESULTS_TEX)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    bundle = load_analysis_bundle(args.bundle)
    render_results_tex(bundle, args.results_tex)
    render_figures(bundle, args.figure_dir)
    print(f"Rendered unfiltered paper assets from {args.bundle}")


if __name__ == "__main__":
    main()
