"""End-to-end pipeline for the main-paper results.

Usage:
    python -m analysis.run                # full run
    python -m analysis.run --skip-perm    # skip Mantel permutation tests (fast)
    python -m analysis.run --skip-mlp     # skip MLP (slower model)

Outputs:
    plots/fig1_dataset_overview.png
    plots/fig2A_semantic_umap.pdf
    plots/fig2B_acoustic_umap.pdf
    plots/fig2C_mantel.pdf
    plots/fig_supp_mantel_matrix.pdf
    plots/pmi_heatmap_paper.{png,pdf}
    plots/fig4_landmark_h.pdf
    paper/paper_macros.tex       (\\nspecies, \\ncalls, … keep main.tex auto-fresh)
    analysis/results.json        (numbers used in paper text / Table 1)
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from analysis import data, embeddings, plotting, predict, stats

ROOT = Path(__file__).resolve().parent.parent
RESULTS_JSON = Path(__file__).resolve().parent / "results.json"
MACROS_TEX = ROOT / "paper" / "paper_macros.tex"


def write_macros(n_species: int, n_calls: int, n_mammals: int, n_birds: int,
                 n_amphib: int, mantel_r: float) -> None:
    MACROS_TEX.parent.mkdir(exist_ok=True)
    MACROS_TEX.write_text(
        "% Auto-generated by analysis/run.py — do not edit by hand.\n"
        f"\\renewcommand{{\\nspecies}}{{{n_species}\\xspace}}\n"
        f"\\renewcommand{{\\ncalls}}{{{n_calls}\\xspace}}\n"
        f"\\newcommand{{\\nmammals}}{{{n_mammals}\\xspace}}\n"
        f"\\newcommand{{\\nbirds}}{{{n_birds}\\xspace}}\n"
        f"\\newcommand{{\\namphibians}}{{{n_amphib}\\xspace}}\n"
        f"\\newcommand{{\\mantelr}}{{{mantel_r:.2f}\\xspace}}\n"
    )


def species_pair_correlation(dist_ac: np.ndarray, dist_sem: np.ndarray,
                              species: list[str]) -> dict[tuple[str, str], float]:
    """Pearson r between acoustic and semantic similarity vectors for every
    species pair (calls in A × calls in B), using all cross-species call pairs."""
    sp_arr = np.array(species)
    sp_list = sorted(set(species))
    sp_to_idx = {s: np.where(sp_arr == s)[0] for s in sp_list}
    out: dict[tuple[str, str], float] = {}
    for i, a in enumerate(sp_list):
        ia = sp_to_idx[a]
        for b in sp_list[i + 1:]:
            ib = sp_to_idx[b]
            ac_block = dist_ac[np.ix_(ia, ib)].ravel()
            sem_block = dist_sem[np.ix_(ia, ib)].ravel()
            if len(ac_block) < 4:
                continue
            out[(a, b)] = stats.pearson_corr(ac_block, sem_block)
    return out


def main(args: argparse.Namespace) -> None:
    print("[1/8] Loading calls …")
    calls = data.load_calls()
    print(f"      {len(calls)} calls from {len({c.species for c in calls})} species")

    print("[2/8] Embedding …")
    sem_emb = embeddings.embed([c.semantic_description for c in calls])
    ac_emb = embeddings.embed([c.acoustic_description for c in calls])

    print("[3/8] Distances + Mantel …")
    dist_sem = stats.cosine_distance(sem_emb)
    dist_ac = stats.cosine_distance(ac_emb)
    sp = np.array([c.species for c in calls])
    fam = np.array([c.family for c in calls])

    iu = np.triu_indices(len(calls), k=1)
    same_sp_pair = (sp[iu[0]] == sp[iu[1]])
    same_fam_pair = (fam[iu[0]] == fam[iu[1]]) & ~same_sp_pair
    cross_fam_pair = ~(same_sp_pair | same_fam_pair)

    nperm = 0 if args.skip_perm else 9999
    r_all, p_all = stats.mantel(dist_ac, dist_sem, n_perm=nperm)
    print(f"      Mantel r(all) = {r_all:.3f}, p = {p_all}")
    # species-identity distance: 0 if same species else 1
    species_dist = (sp[:, None] != sp[None, :]).astype(float)
    r_partial, p_partial = stats.partial_mantel(dist_ac, dist_sem, species_dist,
                                                 n_perm=nperm)

    def _group_r(mask: np.ndarray) -> tuple[float, int]:
        x = dist_ac[iu][mask]; y = dist_sem[iu][mask]
        return stats.pearson_corr(x, y), int(mask.sum())

    r_within, n_within = _group_r(same_sp_pair)
    r_samefam, n_samefam = _group_r(same_fam_pair)
    r_crossfam, n_crossfam = _group_r(cross_fam_pair)

    print("[4/8] Fig 1: dataset overview …")
    plotting.fig1_dataset_overview(calls)

    print("[5/8] Fig 2: UMAPs + Mantel scatter …")
    plotting.fig2_umaps(calls, sem_emb, ac_emb)
    plotting.fig2c_mantel(dist_ac, dist_sem,
                          list(sp), list(fam),
                          r_values={
                              "within species": r_within,
                              "same family": r_samefam,
                              "cross family": r_crossfam,
                          })

    print("[6/8] Species-pairwise Mantel matrix …")
    sp_pair_r = species_pair_correlation(1 - dist_ac, 1 - dist_sem, list(sp))
    species_meta = {c.species: (c.class_, c.family) for c in calls}
    plotting.fig_supp_mantel_matrix(sp_pair_r, species_meta)

    print("[7/8] PMI heatmap …")
    ac_vocab = plotting._flat_acoustic_vocab()
    sem_vocab = plotting._flat_semantic_vocab()
    pmi, _ = stats.pmi_matrix(
        [(c.acoustic_keywords, c.semantic_keywords) for c in calls],
        ac_vocab, sem_vocab, min_count=3,
    )
    plotting.fig_pmi_heatmap(pmi, ac_vocab, sem_vocab)

    print("[7b/8] Landmark cross-species mutual-NN groups …")
    plotting.fig4_landmark(calls, sem_emb, ac_emb)

    print("[8/8] Prediction table …")
    pred = predict.run(ac_emb, sem_emb, list(sp), list(fam))

    # counts
    sp_meta = {c.species: c.class_ for c in calls}
    n_mam = sum(1 for s, cls in sp_meta.items() if cls == "Mammalia")
    n_av = sum(1 for s, cls in sp_meta.items() if cls == "Aves")
    n_am = sum(1 for s, cls in sp_meta.items() if cls == "Amphibia")
    write_macros(len(sp_meta), len(calls), n_mam, n_av, n_am, r_all)

    out = {
        "n_species": len(sp_meta), "n_calls": len(calls),
        "n_mammals": n_mam, "n_birds": n_av, "n_amphibians": n_am,
        "mantel": {
            "r_all": r_all, "p_all": p_all,
            "r_partial_species": r_partial, "p_partial_species": p_partial,
            "r_within_species": r_within, "n_within_species": n_within,
            "r_same_family": r_samefam, "n_same_family": n_samefam,
            "r_cross_family": r_crossfam, "n_cross_family": n_crossfam,
        },
        "prediction": {
            "within": pred.within,
            "held_out_species": pred.held_species,
            "held_out_family": pred.held_family,
        },
    }
    RESULTS_JSON.write_text(json.dumps(out, indent=2))
    print(f"\nWrote {RESULTS_JSON.relative_to(ROOT)}")
    print(f"Wrote {MACROS_TEX.relative_to(ROOT)}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--skip-perm", action="store_true",
                   help="skip Mantel permutation tests")
    p.add_argument("--skip-mlp", action="store_true",
                   help="(reserved) skip MLP model")
    main(p.parse_args())
